sudo: false
language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - TOXENV=django18
    - TOXENV=django19

matrix:
    include:
        - python: "2.7"
          env: TOXENV=flake8
        - python: "2.7"
          env: TOXENV=coverage
install:
    - "pip install tox"

script: "tox -e $TOXENV"
